---
version: '3.8'
services:
  postgres-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    # Instantiate DB with a "raw" schema
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql